[tool.poetry]
name = "quick-node-playground"
version = "0.1.0"
description = "quicknode playground for calling quicknode APIs"
authors = ["eugeneleejunping <eugeneleejunping@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.32.3"
ruff = "^0.4.8"
black = "^24.4.2"
mypy = "1.10.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
