"""add natural key constraints to withdrawals and access list

Revision ID: 779fd1f4899b
Revises: 7b977ba8a1b3
Create Date: 2026-08-31 18:19:48.793358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '779fd1f4899b'
down_revision: Union[str, None] = '7b977ba8a1b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eth_transaction_access_list', sa.Column('item_index', sa.Integer(), nullable=False))
    op.create_unique_constraint('transaction_access_list_transaction_hash_item_index_uq', 'eth_transaction_access_list', ['transaction_hash', 'item_index'])
    op.create_unique_constraint('withdrawals_block_number_index_uq', 'eth_withdrawals', ['block_number', 'index'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('withdrawals_block_number_index_uq', 'eth_withdrawals', type_='unique')
    op.drop_constraint('transaction_access_list_transaction_hash_item_index_uq', 'eth_transaction_access_list', type_='unique')
    op.drop_column('eth_transaction_access_list', 'item_index')
    # ### end Alembic commands ###
