"""create_binance_tables

Revision ID: 820dcfd108c5
Revises: 
Create Date: 2026-03-30 17:54:58.284426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '820dcfd108c5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('binance_klines_prices', sa.Column('number_of_trades', sa.Integer(), nullable=False))
    op.drop_column('binance_klines_prices', 'number of trades')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('binance_klines_prices', sa.Column('number of trades', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('binance_klines_prices', 'number_of_trades')
    # ### end Alembic commands ###
