"""recreate tables

Revision ID: e8d1a0a0bbb9
Revises: 
Create Date: 2026-04-02 20:12:21.025669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8d1a0a0bbb9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_to_s3_import_status',
    sa.Column('data_source', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('kline_open_time', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('data_source', 'symbol', 'kline_open_time')
    )
    op.create_table('s3_to_db_import_status',
    sa.Column('data_source', sa.String(), nullable=False),
    sa.Column('file_modified_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('data_source', 'file_modified_date')
    )
    op.drop_table('s3_import_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('s3_import_status',
    sa.Column('data_source', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_modified_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('data_source', 'file_modified_date', name=op.f('s3_import_status_pkey'))
    )
    op.drop_table('s3_to_db_import_status')
    op.drop_table('provider_to_s3_import_status')
    # ### end Alembic commands ###
