"""added s3_import_status_table

Revision ID: 43622331be5e
Revises: 8e92b22a1afb
Create Date: 2025-01-07 11:41:27.895699

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "43622331be5e"
down_revision: Union[str, None] = "8e92b22a1afb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "s3_import_status",
        sa.Column("data_source", sa.String(), nullable=False),
        sa.Column("file_modified_date", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("data_source", "file_modified_date"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("s3_import_status")
    # ### end Alembic commands ###
